version: 0.0
os: linux
files:
  # unzip en ~/app/release
  - source: /
    destination: /home/ubuntu/app/release
    file_exist_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    # Inicia la aplicación com ubuntu
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
  # Para la aplicación
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root